Repository VultureProject/vulture-gui, pull requests merged in 2021-06, with the labels that each got.

#108 GUI_DARWIN::MODIFIED:: Can always set enrichment tags to a filter, those tags will always be in the alert
  vulture_os/darwin/policy/models.py
  vulture_os/darwin/templates/policy_edit_v2.html
  vulture_os/gui/static/js/darwin_policy_edit.js
Labels: enhancement

#122 Release 1.2.8
  vulture_os/applications/backend/form.py
  vulture_os/applications/backend/views.py
  vulture_os/applications/logfwd/config/om_fwd.tpl
  vulture_os/applications/logfwd/form.py
  vulture_os/applications/logfwd/models.py
  vulture_os/applications/migrations/0015_logomfwd_send_as_raw.py
  vulture_os/applications/templates/apps/logfwd_LogOMFWD.html
  vulture_os/authentication/ldap/tools.py
  vulture_os/authentication/ldap/views.py
  vulture_os/authentication/learning_profiles/models.py
  vulture_os/authentication/templates/authentication/ldap_edit.html
  vulture_os/authentication/templates/authentication/user_authentication_edit.html
  vulture_os/authentication/user_portal/models.py
  vulture_os/authentication/user_portal/views.py
  vulture_os/daemons/monitor.py
  vulture_os/darwin/access_control/form.py
  vulture_os/darwin/access_control/models.py
  vulture_os/darwin/migrations/0011_remove_accesscontrol_enabled.py
  vulture_os/darwin/policy/models.py
  vulture_os/darwin/templates/access_control.html
  vulture_os/darwin/templates/access_control_edit.html
  vulture_os/darwin/templates/policy_edit_v2.html
  vulture_os/gui/static/js/darwin_policy_edit.js
  vulture_os/gui/static/js/listener.js
  vulture_os/gui/views/install.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/system/self_actions.py
  vulture_os/portal/system/sso_forwards.py
  vulture_os/portal/views/logon.py
  vulture_os/portal/views/responses.py
  vulture_os/services/config/rsyslog_inputs.conf
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0031_frontend_kafka_options.py
  vulture_os/services/strongswan/api.py
  vulture_os/services/strongswan/models.py
  vulture_os/services/strongswan/urls.py
  vulture_os/services/strongswan/views.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/symantec/symantec.py
  vulture_os/toolkit/updates/v1.2.8/0_fix_portal_template.py
  vulture_os/toolkit/updates/v1.2.8/1_reload_frontends_auth_conf.py
  vulture_os/workflow/api.py
  vulture_os/workflow/templates/main/workflow.html
  vulture_os/workflow/views.py
Labels: bug, enhancement

#124 Version 1.2.9
  vulture_os/authentication/generic_delete.py
  vulture_os/authentication/ldap/tools.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/user_portal/views.py
Labels: bug

#125 Release 1.2.9
  vulture_os/authentication/base_repository.py
  vulture_os/authentication/generic_delete.py
  vulture_os/authentication/ldap/tools.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/user_portal/views.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/self_actions.py
  vulture_os/portal/views/logon.py
  vulture_os/portal/views/responses.py
  vulture_os/portal/views/self.py
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0032_auto_20210423_1539.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/netskope/__init__.py
  vulture_os/toolkit/api_parser/netskope/netskope.py
  vulture_os/toolkit/api_parser/utils.py
  vulture_os/toolkit/auth/ldap_client.py
  vulture_os/toolkit/updates/v1.2.9/0_fix_frontends.py
Labels: bug, enhancement

#127 Hotfix 1.2.9_1
  vulture_os/toolkit/api_parser/netskope/netskope.py
Labels: bug

#126 Darwin : avoid recreating filters when editing policies
  vulture_os/darwin/policy/api.py
  vulture_os/gui/static/js/darwin_policy_edit.js
  vulture_os/services/config/darwin.conf
  vulture_os/services/rsyslogd/config/rsyslog_darwin/ruleset.conf
Labels: bug

#130 Release 1.2.11
  vulture_os/authentication/authentication.py
  vulture_os/authentication/generic_delete.py
  vulture_os/authentication/generic_list.py
  vulture_os/authentication/migrations/0012_auto_20210615_1732.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/templates/authentication/openid_edit.html
  vulture_os/authentication/templates/authentication/user_authentication_edit.html
  vulture_os/authentication/templates/authentication/user_scope.html
  vulture_os/authentication/templates/authentication/user_scope_edit.html
  vulture_os/authentication/user_portal/form.py
  vulture_os/authentication/user_portal/models.py
  vulture_os/authentication/user_portal/views.py
  vulture_os/authentication/user_scope/__init__.py
  vulture_os/authentication/user_scope/api.py
  vulture_os/authentication/user_scope/form.py
  vulture_os/authentication/user_scope/models.py
  vulture_os/authentication/user_scope/urls.py
  vulture_os/authentication/user_scope/views.py
  vulture_os/portal/views/logon.py
Labels: enhancement
