Repository VultureProject/vulture-gui, pull requests merged in 2021-07, with the labels that each got.

#131 Portal : Allow session refresh during requests
  vulture_os/authentication/templates/authentication/user_authentication_edit.html
  vulture_os/authentication/user_portal/views.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/views/logon.py
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
Labels: bug, enhancement

#133 Beta 1.3.0
  vulture_os/authentication/auth_access_control/api.py
  vulture_os/authentication/auth_access_control/form.py
  vulture_os/authentication/auth_access_control/models.py
  vulture_os/authentication/auth_access_control/views.py
  vulture_os/authentication/generic_delete.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/portal.py
  vulture_os/authentication/portal_template/models.py
  vulture_os/authentication/templates/authentication/access_control/edit.html
  vulture_os/authentication/templates/authentication/user_authentication_edit.html
  vulture_os/authentication/user_portal/models.py
  vulture_os/authentication/user_portal/views.py
  vulture_os/gui/static/js/portal/auth_access_control.js
  vulture_os/gui/static/js/workflow.js
  vulture_os/gui/static/js/workflow_form.js
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/views/logon.py
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/toolkit/auth/ldap_client.py
  vulture_os/workflow/api.py
  vulture_os/workflow/models.py
  vulture_os/workflow/templates/main/workflow_edit.html
  vulture_os/workflow/views.py
Labels: bug, enhancement

#134 Release 1.3.0
  vulture_os/authentication/auth_access_control/api.py
  vulture_os/authentication/auth_access_control/form.py
  vulture_os/authentication/auth_access_control/models.py
  vulture_os/authentication/auth_access_control/views.py
  vulture_os/authentication/generic_delete.py
  vulture_os/authentication/idp/api.py
  vulture_os/authentication/ldap/tools.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/portal.py
  vulture_os/authentication/portal_template/models.py
  vulture_os/authentication/templates/authentication/access_control/edit.html
  vulture_os/authentication/templates/authentication/user_authentication_edit.html
  vulture_os/authentication/templates/authentication/user_scope.html
  vulture_os/authentication/templates/authentication/user_scope_edit.html
  vulture_os/authentication/user_portal/models.py
  vulture_os/authentication/user_portal/views.py
  vulture_os/authentication/user_scope/urls.py
  vulture_os/authentication/user_scope/views.py
  vulture_os/gui/static/js/portal/auth_access_control.js
  vulture_os/gui/static/js/workflow.js
  vulture_os/gui/static/js/workflow_form.js
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/views/logon.py
  vulture_os/services/config/filebeat_input.conf
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
  vulture_os/toolkit/auth/ldap_client.py
  vulture_os/toolkit/updates/v1.3.0/0_generate_filebeat_config.py
  vulture_os/toolkit/updates/v1.3.0/1_refresh_spoe_session.py
  vulture_os/toolkit/updates/v1.3.0/2_reload_frontends_auth_conf.py
  vulture_os/workflow/api.py
  vulture_os/workflow/migrations/0006_auto_20210701_0205.py
  vulture_os/workflow/models.py
  vulture_os/workflow/templates/main/workflow_edit.html
  vulture_os/workflow/views.py
Labels: bug, enhancement

#135 Release 1.3.1
  vulture_os/authentication/idp/api.py
  vulture_os/authentication/migrations/0013_auto_20210709_0527.py
  vulture_os/authentication/user_portal/models.py
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/toolkit/network/smtp.py
  vulture_os/toolkit/updates/v1.3.1/0_refresh_spoe_session.py
  vulture_os/toolkit/updates/v1.3.1/1_reload_frontends_auth_conf.py
Labels: bug, enhancement

#136 Release 1.3.2
  vulture_os/applications/reputation_ctx/config/haproxy_backend.conf
  vulture_os/authentication/portal_template/config/haproxy_backend.conf
  vulture_os/authentication/user_portal/config/haproxy_portal.conf
  vulture_os/authentication/user_portal/views.py
  vulture_os/darwin/access_control/config/haproxy_test.conf
  vulture_os/darwin/log_viewer/config/haproxy_backend_defender.conf
  vulture_os/darwin/log_viewer/config/haproxy_spoe_defender.conf
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/haproxy/models.py
  vulture_os/toolkit/updates/v1.3.2/0_refresh_spoe_session.py
  vulture_os/toolkit/updates/v1.3.2/1_reload_frontends_auth_conf.py
  vulture_os/toolkit/updates/v1.3.2/2_reload_backends_conf.py
  vulture_os/toolkit/updates/v1.3.2/3_reload_portals_conf.py
  vulture_os/workflow/config/haproxy_portal.conf
  vulture_os/workflow/views.py
Labels: bug

#137 Release 1.3.3
  home/jails.apache/.zfs-source/usr/local/etc/apache24/portal-httpd.conf
  vulture_os/authentication/user_portal/config/haproxy_portal.conf
  vulture_os/toolkit/updates/v1.3.3/0_reload_haproxy_auth.py
  vulture_os/toolkit/updates/v1.3.3/1_update_portal-httpd_config.sh
  vulture_os/workflow/config/haproxy_portal.conf
Labels: enhancement
