Repository VultureProject/vulture-gui, pull requests merged in 2021-03, with the labels that each got.

#81 Add support for imhiredis in GUI. Add a small helper message in not_i…
  vulture_os/gui/static/js/listener.js
  vulture_os/gui/templates/gui/not_install.html
  vulture_os/services/config/rsyslog_inputs.conf
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
  vulture_os/services/templates/services/frontend_edit.html
Labels: feature

#85 Version 1.1.5
  vulture_os/gui/static/css/custom.css
  vulture_os/gui/static/js/listener.js
  vulture_os/gui/static/js/log_viewer.js
  vulture_os/gui/templates/gui/not_install.html
  vulture_os/services/config/rsyslog_inputs.conf
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
  vulture_os/services/migrations/0028_auto_20210308_1623.py
  vulture_os/services/templates/services/frontend_edit.html
Labels: bug, feature

#90 Release 1.2.1
  vulture_os/authentication/migrations/0005_auto_20210317_0955.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/templates/authentication/openid_edit.html
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0029_auto_20210317_0955.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/sentinel_one/__init__.py
  vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
  vulture_os/toolkit/api_parser/utils.py
Labels: enhancement
