Repository VultureProject/vulture-gui, pull requests merged in 2022-07, with the labels that each got.

#211 Fix Api-harfanglab replay
  vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
Labels: bug

#210 Beta 1.15.0
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0044_auto_20220707_0817.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/gsuite_alertcenter/__init__.py
  vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
  vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
  vulture_os/toolkit/api_parser/utils.py
Labels: enhancement

#215 New api collector sophos_cloud
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/sophos_cloud/__init__.py
  vulture_os/toolkit/api_parser/sophos_cloud/sophos_cloud.py
  vulture_os/toolkit/api_parser/utils.py
Labels: enhancement

#217 Beta 1.16.0
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0045_auto_20220713_1437.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/sophos_cloud/__init__.py
  vulture_os/toolkit/api_parser/sophos_cloud/sophos_cloud.py
  vulture_os/toolkit/api_parser/utils.py
Labels: enhancement

#218 Release 1.16.0
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0045_auto_20220713_1437.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/sophos_cloud/__init__.py
  vulture_os/toolkit/api_parser/sophos_cloud/sophos_cloud.py
  vulture_os/toolkit/api_parser/utils.py
Labels: enhancement

#219 Release 1.16.1
  vulture_os/services/frontend/form.py
Labels: bug

#221 Session oauth check
  .gitignore
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/user_portal/models.py
  vulture_os/gui/views/install.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/views/logon.py
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
  vulture_os/services/haproxy/haproxy.py
  vulture_os/services/haproxy/models.py
  vulture_os/toolkit/portal/pkce.py
  vulture_os/toolkit/updates/v1.17.0/0_reload_haproxy_confs.py
  vulture_os/workflow/api.py
  vulture_os/workflow/models.py
  vulture_os/workflow/views.py
Labels: bug, enhancement, feature, Important
