Repository VultureProject/vulture-gui, pull requests merged in 2022-02, with the labels that each got.

#167 Release 1.6.1
  vulture_os/authentication/base_repository.py
  vulture_os/authentication/idp/api.py
  vulture_os/authentication/ldap/tools.py
  vulture_os/authentication/migrations/0016_auto_20211206_1240.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/otp/api.py
  vulture_os/authentication/portal_template/models.py
  vulture_os/authentication/user_portal/models.py
  vulture_os/authentication/user_portal/views.py
  vulture_os/darwin/policy/api.py
  vulture_os/gui/crontab/api_clients_parser.py
  vulture_os/gui/crontab/feed.py
  vulture_os/gui/views/install.py
  vulture_os/portal/settings.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/exceptions.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/system/self_actions.py
  vulture_os/portal/system/sso_clients.py
  vulture_os/portal/system/sso_forwards.py
  vulture_os/portal/views/logon.py
  vulture_os/portal/views/responses.py
  vulture_os/portal/views/self.py
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
  vulture_os/services/haproxy/haproxy.py
  vulture_os/system/cluster/api.py
  vulture_os/system/cluster/models.py
  vulture_os/system/cluster/urls.py
  vulture_os/toolkit/api_parser/vadesecure/vadesecure.py
  vulture_os/toolkit/auth/ldap_client.py
  vulture_os/toolkit/auth/totp_client.py
  vulture_os/toolkit/portal/registration.py
  vulture_os/toolkit/redis/redis_base.py
  vulture_os/toolkit/system/aes_utils.py
  vulture_os/toolkit/system/secret_key.py
  vulture_os/toolkit/updates/v1.6.1/0_reload_aes_values_totp.py
  vulture_os/toolkit/updates/v1.6.1/1_reload_aes_values_learning_profiles.py
  vulture_os/toolkit/updates/v1.6.1/2_reload_frontends_conf.py
  vulture_os/toolkit/updates/v1.6.1/3_fix_portal_template.py
  vulture_os/vulture_os/settings.py
Labels: bug, enhancement

#168 Release 1.7.0
  home/jails.apache/.zfs-source/usr/local/etc/gunicorn.d/portal.conf.py
  home/jails.apache/.zfs-source/usr/local/etc/rc.d/gunicorn
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/toolkit/updates/v1.7.0/0_migrate_portal_gunicorn.sh
  vulture_os/toolkit/updates/v1.7.0/1_reload_frontends_conf.py
Labels: enhancement

#171 GUNICORN::FIXED:: gunicorn did not listen on IPv6 jail address
  home/jails.apache/.zfs-source/usr/local/etc/gunicorn.d/portal.conf.py
Labels: bug

#169 API_URLS::ADDED:: URLs with and without trailing '/' to uniformize
  vulture_os/authentication/auth_access_control/urls.py
  vulture_os/authentication/idp/urls.py
  vulture_os/authentication/portal_template/urls.py
  vulture_os/darwin/defender_policy/urls.py
  vulture_os/darwin/policy/urls.py
  vulture_os/gui/urls.py
  vulture_os/system/tenants/urls.py
  vulture_os/system/vm/urls.py
  vulture_os/system/zfs/urls.py
Labels: bug

#173 Release 1.7.1
  home/jails.apache/.zfs-source/usr/local/etc/gunicorn.d/portal.conf.py
  vulture_os/authentication/auth_access_control/urls.py
  vulture_os/authentication/idp/urls.py
  vulture_os/authentication/portal_template/urls.py
  vulture_os/darwin/defender_policy/urls.py
  vulture_os/darwin/policy/urls.py
  vulture_os/gui/urls.py
  vulture_os/system/tenants/urls.py
  vulture_os/system/vm/urls.py
  vulture_os/system/zfs/urls.py
Labels: bug
