Repository VultureProject/vulture-gui, pull requests merged in 2022-03, with the labels that each got.

#177 Release 1.9.0
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0039_auto_20220223_1555.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/nozomi_probe/__init__.py
  vulture_os/toolkit/api_parser/nozomi_probe/nozomi_probe.py
  vulture_os/toolkit/api_parser/utils.py
Labels: enhancement

#178 API_PARSER::ADDED:: New API parser Blackberry Cylance
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/blackberry_cylance/__init__.py
  vulture_os/toolkit/api_parser/blackberry_cylance/blackberry_cylance.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#181 Beta 1.10.0: new API parser blackberry Cylance
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0040_auto_20220317_0822.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/blackberry_cylance/__init__.py
  vulture_os/toolkit/api_parser/blackberry_cylance/blackberry_cylance.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#161 ACLs corrections
  vulture_os/applications/backend/config/haproxy_backend.conf
  vulture_os/applications/backend/models.py
  vulture_os/darwin/access_control/models.py
  vulture_os/gui/static/js/access_control.js
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
  vulture_os/workflow/models.py
Labels: bug

#182 Release 1.10.0
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/migrations/0040_auto_20220317_0822.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/blackberry_cylance/__init__.py
  vulture_os/toolkit/api_parser/blackberry_cylance/blackberry_cylance.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#180 Portal fixes
  vulture_os/authentication/idp/api.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/system/self_actions.py
  vulture_os/portal/views/logon.py
  vulture_os/toolkit/auth/ldap_client.py
Labels: bug

#179 API SENTINEL ONE: Fixes and improvements
  vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
Labels: bug

#185 Version 1.11.0
  home/jails.apache/.zfs-source/home/vlt-os/scripts/replica_rename.py
  vulture_os/applications/backend/config/haproxy_backend.conf
  vulture_os/applications/backend/models.py
  vulture_os/authentication/idp/api.py
  vulture_os/darwin/access_control/models.py
  vulture_os/darwin/access_control/views.py
  vulture_os/gui/static/js/access_control.js
  vulture_os/gui/views/install.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/system/self_actions.py
  vulture_os/portal/views/logon.py
  vulture_os/services/config/haproxy_internal_portals.conf
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
  vulture_os/services/haproxy/haproxy.py
  vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
  vulture_os/toolkit/auth/ldap_client.py
  vulture_os/toolkit/updates/v1.11.0/0_reload_haproxy_auth.py
  vulture_os/workflow/api.py
  vulture_os/workflow/config/haproxy_portal.conf
  vulture_os/workflow/models.py
  vulture_os/workflow/views.py
Labels: bug, enhancement
