Repository VultureProject/vulture-gui, pull requests merged in 2022-08, with the labels that each got.

#229 Version 1.17.0
  vulture_os/toolkit/api_parser/gsuite_alertcenter/gsuite_alertcenter.py
  vulture_os/toolkit/api_parser/office365/office365.py
  vulture_os/toolkit/api_parser/proofpoint_pod/proofpoint_pod.py
  vulture_os/toolkit/api_parser/sophos_cloud/sophos_cloud.py
  vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
  vulture_os/toolkit/updates/v1.17.0/0_update_api_parsers.py
Labels: enhancement, Important

#232 Beta 1.18.0
  .gitignore
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/openid/views.py
  vulture_os/authentication/user_portal/models.py
  vulture_os/gui/views/install.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/views/logon.py
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
  vulture_os/services/haproxy/haproxy.py
  vulture_os/services/haproxy/models.py
  vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
  vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
  vulture_os/toolkit/portal/pkce.py
  vulture_os/toolkit/updates/v1.17.0/0_reload_haproxy_confs.py
  vulture_os/workflow/api.py
  vulture_os/workflow/models.py
  vulture_os/workflow/views.py
Labels: bug, enhancement, feature

#233 Version 1.18.0
  .gitignore
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/openid/views.py
  vulture_os/authentication/user_portal/config/haproxy_portal.conf
  vulture_os/authentication/user_portal/models.py
  vulture_os/gui/views/install.py
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/views/logon.py
  vulture_os/services/config/spoe_session.txt
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
  vulture_os/services/haproxy/haproxy.py
  vulture_os/services/haproxy/models.py
  vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
  vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
  vulture_os/toolkit/portal/pkce.py
  vulture_os/toolkit/updates/v1.18.0/0_reload_haproxy_confs.py
  vulture_os/workflow/api.py
  vulture_os/workflow/models.py
  vulture_os/workflow/views.py
Labels: bug, enhancement, feature

#243 HARFANGLAB - Prevent duplicated alerts
  vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
Labels: bug
