Repository VultureProject/vulture-gui, pull requests merged in 2023-12, with the labels that each got.

#387 [FORCEPOINT] Fix redis lock handling (doublon process)
  CHANGELOG
  vulture_os/toolkit/api_parser/forcepoint/forcepoint.py
Labels: bug

#386 [FRONTEND] Deploy a listener on every node when listening_node is empty
  CHANGELOG
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
  vulture_os/services/rsyslogd/models.py
Labels: enhancement

#382 [API_PARSER][SIGNALSCIENCES_NGWAF] New collector
  CHANGELOG
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/signalsciences_ngwaf/signalsciences_ngwaf.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#385 [HAPROXY] JWT verification
  CHANGELOG
  vulture_os/authentication/migrations/0023_typo_jwt_signature_type_choices.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/openid/views.py
  vulture_os/authentication/templates/authentication/openid_edit.html
  vulture_os/authentication/user_portal/models.py
  vulture_os/portal/system/sso_forwards.py
  vulture_os/portal/views/logon.py
  vulture_os/system/config/models.py
  vulture_os/workflow/config/haproxy_portal.conf
  vulture_os/workflow/models.py
Labels: feature
