Repository VultureProject/vulture-gui, pull requests merged in 2023-11, with the labels that each got.

#370 [FRONTEND] New last_update_time field
  CHANGELOG
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
Labels: feature

#371 [LOGOM] Fix bugs related to names and dependencies
  CHANGELOG
  vulture_os/applications/logfwd/views.py
  vulture_os/services/frontend/models.py
Labels: bug

#373 [HAPROXY] Split Frontend and Workflow config to improve performance
  CHANGELOG
  vulture_os/authentication/user_portal/config/haproxy_portal.conf
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/workflow/config/haproxy_portal.conf
  vulture_os/workflow/models.py
Labels: enhancement

#374 [WORKFLOW] Add CORS policy settings
  CHANGELOG
  vulture_os/gui/static/js/workflow.js
  vulture_os/gui/static/js/workflow_form.js
  vulture_os/workflow/config/haproxy_portal.conf
  vulture_os/workflow/form.py
  vulture_os/workflow/models.py
  vulture_os/workflow/templates/main/workflow_edit.html
  vulture_os/workflow/views.py
Labels: feature

#376 SYSTEM::FIXED: change password of an existing user
  CHANGELOG
  vulture_os/gui/forms/user_form.py
  vulture_os/system/users/form.py
  vulture_os/system/users/views.py
Labels: bug

#378 [API_PARSER][HARFANGLAB] Evol:: Add threats endpoint
  CHANGELOG
  vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
Labels: feature

#379 [FRONTEND][TCP] Add advanced option 'custom_tl_frame_delimiter'
  CHANGELOG
  vulture_os/services/config/rsyslog_inputs.conf
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
Labels: enhancement
