Repository VultureProject/vulture-gui, pull requests merged in 2023-07, with the labels that each got.

#328 CERTS::FIXED: protect used certificates on delete request
  CHANGELOG
  vulture_os/system/pki/views.py
Labels: bug

#330 [LOGFORWARDER] Fix logforward to elastic8
  CHANGELOG
  vulture_os/applications/logfwd/config/om_elasticsearch.tpl
  vulture_os/applications/logfwd/form.py
  vulture_os/applications/logfwd/models.py
  vulture_os/applications/templates/apps/logfwd_LogOMElasticSearch.html
Labels: bug

#332 [ACLS] Rebuild haproxy conf on acl change
  CHANGELOG
  vulture_os/darwin/access_control/views.py
  vulture_os/gui/static/js/workflow.js
Labels: bug

#275 [PORTAL][IDP] Refresh token Grant Type
  CHANGELOG
  vulture_os/authentication/migrations/0020_auto_20230607_1528.py
  vulture_os/authentication/templates/authentication/user_authentication_edit.html
  vulture_os/authentication/user_portal/config/haproxy_portal.conf
  vulture_os/authentication/user_portal/form.py
  vulture_os/authentication/user_portal/models.py
  vulture_os/gui/static/js/portal/template_edit.js
  vulture_os/portal/system/authentications.py
  vulture_os/portal/system/redis_sessions.py
  vulture_os/portal/views/logon.py
  vulture_os/workflow/config/haproxy_portal.conf
Labels: feature

#323 [API_PARSER][SAFENET] Increment last_api_call if no logs
  vulture_os/toolkit/api_parser/safenet/safenet.py
Labels: bug

#326 [API_PARSER][CSC_DOMAINMANAGER] NEW collector
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/csc_domainmanager/__init__.py
  vulture_os/toolkit/api_parser/csc_domainmanager/csc_domainmanager.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#327 [API_PARSER][IMPERVA] Fixes
  vulture_os/toolkit/api_parser/imperva/imperva.py
Labels: bug, Need changes

#334 [API_PARSER][CYBEREASON] FIx timestamp for `malware` logs
  vulture_os/toolkit/api_parser/cybereason/cybereason.py
Labels: bug

#331 [CERTIFICATES] Reload haproxy on pki change
  CHANGELOG
  vulture_os/system/pki/views.py
Labels: bug
