Repository VultureProject/vulture-gui, pull requests merged in 2023-08, with the labels that each got.

#321 [FRONTEND] Support api parser with custom certificate
  CHANGELOG
  vulture_os/gui/static/js/listener.js
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/system/pki/models.py
  vulture_os/system/templates/system/pki_edit.html
  vulture_os/toolkit/api_parser/akamai/akamai.py
  vulture_os/toolkit/api_parser/api_parser.py
  vulture_os/toolkit/api_parser/aws_bucket/aws_bucket.py
  vulture_os/toolkit/api_parser/blackberry_cylance/blackberry_cylance.py
  vulture_os/toolkit/api_parser/carbon_black/carbon_black.py
  vulture_os/toolkit/api_parser/cisco_duo/cisco_duo.py
  vulture_os/toolkit/api_parser/cortex_xdr/cortex_xdr.py
  vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py
  vulture_os/toolkit/api_parser/csc_domainmanager/csc_domainmanager.py
  vulture_os/toolkit/api_parser/cybereason/cybereason.py
  vulture_os/toolkit/api_parser/defender_atp/defender_atp.py
  vulture_os/toolkit/api_parser/forcepoint/forcepoint.py
  vulture_os/toolkit/api_parser/harfanglab/harfanglab.py
  vulture_os/toolkit/api_parser/imperva/imperva.py
  vulture_os/toolkit/api_parser/mongodb/mongodb.py
  vulture_os/toolkit/api_parser/ms_sentinel/ms_sentinel.py
  vulture_os/toolkit/api_parser/netskope/netskope.py
  vulture_os/toolkit/api_parser/nozomi_probe/nozomi_probe.py
  vulture_os/toolkit/api_parser/office365/office365.py
  vulture_os/toolkit/api_parser/proofpoint_casb/proofpoint_casb.py
  vulture_os/toolkit/api_parser/proofpoint_tap/proofpoint_tap.py
  vulture_os/toolkit/api_parser/proofpoint_trap/proofpoint_trap.py
  vulture_os/toolkit/api_parser/rapid7_idr/rapid7_idr.py
  vulture_os/toolkit/api_parser/reachfive/reachfive.py
  vulture_os/toolkit/api_parser/safenet/safenet.py
  vulture_os/toolkit/api_parser/sentinel_one/sentinel_one.py
  vulture_os/toolkit/api_parser/sentinel_one_mobile/sentinel_one_mobile.py
  vulture_os/toolkit/api_parser/symantec/symantec.py
  vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
  vulture_os/toolkit/api_parser/trendmicro_worryfree/trendmicro_worryfree.py
  vulture_os/toolkit/api_parser/utils.py
  vulture_os/toolkit/api_parser/vadesecure/vadesecure.py
  vulture_os/toolkit/api_parser/vadesecure_o365/vadesecure_o365.py
  vulture_os/toolkit/api_parser/waf_cloud_protector/waf_cloud_protector.py
  vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
Labels: enhancement, Need Update

#344 [FRONTEND] Disable logforwarder if logging disabled
  CHANGELOG
  vulture_os/gui/static/js/listener.js
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
Labels: bug

#335 [LOGFORWARDER] implements new send_as_raw feature for LogForwarder in gui
  CHANGELOG
  vulture_os/applications/logfwd/config/om_elasticsearch.tpl
  vulture_os/applications/logfwd/config/om_file.tpl
  vulture_os/applications/logfwd/config/om_hiredis.tpl
  vulture_os/applications/logfwd/config/om_mongodb.tpl
  vulture_os/applications/logfwd/config/om_relp.tpl
  vulture_os/applications/logfwd/form.py
  vulture_os/applications/logfwd/models.py
  vulture_os/applications/templates/apps/logfwd_LogOMElasticSearch.html
  vulture_os/applications/templates/apps/logfwd_LogOMFile.html
  vulture_os/applications/templates/apps/logfwd_LogOMHIREDIS.html
  vulture_os/applications/templates/apps/logfwd_LogOMMongoDB.html
  vulture_os/applications/templates/apps/logfwd_LogOMRELP.html
Labels: feature

#333 [CLUSTER] Node state and API collector runner selector
  CHANGELOG
  vulture_os/daemons/monitor.py
  vulture_os/gui/crontab/api_clients_parser.py
  vulture_os/gui/management/commands/toggle_maintenance.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/system/cluster/models.py
  vulture_os/system/templates/system/cluster.html
Labels: feature, Need changes
