Repository VultureProject/vulture-gui, pull requests merged in 2023-10, with the labels that each got.

#345 [WORKFLOW] Add type change check when front/back associated to workflow
  CHANGELOG
  vulture_os/applications/backend/views.py
  vulture_os/services/frontend/views.py
Labels: bug

#350 [API_COLLECTOR][CISCO_DUO] Fix log.metadata null check
  CHANGELOG
  vulture_os/toolkit/api_parser/cisco_duo/cisco_duo.py
Labels: bug

#356 [API_COLLECTOR][CSC_DOMAINMANAGER] Fix stagnation if no log during last 24H
  CHANGELOG
  vulture_os/toolkit/api_parser/csc_domainmanager/csc_domainmanager.py
Labels: bug

#357 [API_COLLECTOR][VADESECURE] Evolution to use accountId inherited from admin parent
  CHANGELOG
  vulture_os/toolkit/api_parser/vadesecure/vadesecure.py
Labels: enhancement

#355 [FRONTEND] Custom proxy for api parser
  CHANGELOG
  vulture_os/gui/static/js/listener.js
  vulture_os/services/config/filebeat_inputs.conf
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/api_parser.py
  vulture_os/toolkit/network/network.py
Labels: enhancement

#369 [MS_SENTINEL] Evol to use new alert_time as outdated alert check & fix entities gathering
  CHANGELOG
  vulture_os/toolkit/api_parser/ms_sentinel/ms_sentinel.py
Labels: bug, enhancement

#359 [PORTAL][IDP] Add new option JWT Authorization in GUI
  CHANGELOG
  vulture_os/authentication/migrations/0022_auto_20231005_0916.py
  vulture_os/authentication/openid/form.py
  vulture_os/authentication/openid/models.py
  vulture_os/authentication/templates/authentication/openid_edit.html
  vulture_os/authentication/templates/authentication/user_authentication.html
Labels: feature

#360 [PORTAL] Add /userinfo authentication using JWT
  CHANGELOG
  vulture_os/portal/settings.py
  vulture_os/portal/views/logon.py
Labels: feature
