Repository VultureProject/vulture-gui, pull requests merged in 2024-09, with the labels that each got.

#434 [TENANTS] New additional_config field
  CHANGELOG
  vulture_os/system/migrations/0025_tenants_custom_config.py
  vulture_os/system/templates/system/tenants_edit.html
  vulture_os/system/tenants/api.py
  vulture_os/system/tenants/form.py
  vulture_os/system/tenants/models.py
  vulture_os/system/tenants/views.py
  vulture_os/toolkit/updates/v2.16.0/0_transfer_tenants_config.py
Labels: enhancement

#444 [GUI] [FRONTEND] Remove too strict validation for log_condition field
  CHANGELOG
  vulture_os/services/frontend/form.py
Labels: bug

#454 [API_PARSER][CYBEREASON] Fix multiple points
  CHANGELOG
  vulture_os/toolkit/api_parser/cybereason/cybereason.py
Labels: bug

#449 [API_PARSER][REACHFIVE] Store access token & avoid too many request or too large …
  CHANGELOG
  vulture_os/services/frontend/models.py
  vulture_os/toolkit/api_parser/reachfive/reachfive.py
Labels: bug

#447 [API_PARSER][BEYONDTRUST_PRA] New API parser BEYONDTRUST_PRA
  CHANGELOG
  requirements.in
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/beyondtrust_pra/__init__.py
  vulture_os/toolkit/api_parser/beyondtrust_pra/beyondtrust_pra.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature
