Repository VultureProject/vulture-gui, pull requests merged in 2025-04, with the labels that each got.

#515 [API_PARSER][PERCEPTION POINT X RAY] New collector for Perception Point X Ray
  CHANGELOG
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/perception_point_x_ray/__init__.py
  vulture_os/toolkit/api_parser/perception_point_x_ray/perception_point_x_ray.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#528 [API_PARSER][EXTRAHOP] New collector
  CHANGELOG
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/extrahop/__init__.py
  vulture_os/toolkit/api_parser/extrahop/extrahop.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#440 [FRONTEND] Correctly play/pause Frontends manually
  CHANGELOG
  vulture_os/applications/logfwd/models.py
  vulture_os/daemons/monitor.py
  vulture_os/services/config/rsyslog_inputs.conf
  vulture_os/services/filebeat/filebeat.py
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
  vulture_os/services/haproxy/haproxy.py
  vulture_os/services/templates/services/frontends.html
  vulture_os/system/config/views.py
  vulture_os/toolkit/updates/v1.3.7/1_upgrade_filebeat_confs.py
  vulture_os/toolkit/updates/v1.3.9/1_upgrade_filebeat_confs.py
  vulture_os/toolkit/updates/v2.10.2/1_reload_log_filebeat_redis_frontends.py
Labels: enhancement

#532 fix(frontend): haproxy config generation failure with new frontends
  vulture_os/services/frontend/config/haproxy_frontend.conf
  vulture_os/services/frontend/models.py
Labels: bug

#536 [API_PARSER][CISCO_MERAKI] Add support of configuration change logs
  CHANGELOG
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/cisco_meraki/cisco_meraki.py
Labels: feature

#427 [PORTAL] [SELF_SERVICE] Disabled workflows listed
  CHANGELOG
  vulture_os/portal/system/self_actions.py
Labels: bug

#534 fix(mongodb): Allow clusters with more than 7 nodes
  CHANGELOG
  vulture_os/toolkit/mongodb/mongo_base.py
Labels: bug

#523 fix(services): weird bug in djongo
  CHANGELOG
  vulture_os/gui/static/js/darwin_policy_edit.js
  vulture_os/services/frontend/models.py
  vulture_os/services/rsyslogd/rsyslog.py
Labels: bug
