Repository VultureProject/vulture-gui, pull requests merged in 2025-03, with the labels that each got.

#510 [API_PARSER][CISCO_MERAKI] Fix and logger
  CHANGELOG
  vulture_os/toolkit/api_parser/cisco_meraki/cisco_meraki.py
Labels: bug

#518 [API_PARSER][GATEWATCHER_ALERTS] Add 'host' field in json logs
  CHANGELOG
  vulture_os/toolkit/api_parser/gatewatcher_alerts/gatewatcher_alerts.py
Labels: enhancement

#519 [API_PARSER][WAF_CLOUDFLARE] Fix invalid 'test' time range
  CHANGELOG
  vulture_os/toolkit/api_parser/waf_cloudflare/waf_cloudflare.py
Labels: bug

#522 [API_PARSER][CYBEREASON] Catch 204,500 HTTP codes
  CHANGELOG
  vulture_os/toolkit/api_parser/cybereason/cybereason.py
  vulture_os/toolkit/api_parser/cybereason/malop.py
Labels: bug

#507 [API_PARSER][ARMIS_CENTRIX] Create new collector for Armis Centrix EDR (Alerts & Activity)
  CHANGELOG
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/armis_centrix/__init__.py
  vulture_os/toolkit/api_parser/armis_centrix/armis_centrix.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#527 fix(frontend): unable to delete config files due to wrong mode filtering
  CHANGELOG
  vulture_os/services/frontend/models.py
  vulture_os/services/frontend/views.py
Labels: bug
