Repository VultureProject/vulture-gui, pull requests merged in 2025-05, with the labels that each got.

#529 [CROWDSTRIKE] Migrate v1->v2 endpoints
  CHANGELOG
  vulture_os/toolkit/api_parser/crowdstrike/crowdstrike.py
Labels: breaking

#547 [HORNETSECURITY] New collector
  CHANGELOG
  vulture_os/services/frontend/form.py
  vulture_os/services/frontend/models.py
  vulture_os/services/templates/services/frontend_edit.html
  vulture_os/toolkit/api_parser/hornetsecurity/__init__.py
  vulture_os/toolkit/api_parser/hornetsecurity/hornetsecurity.py
  vulture_os/toolkit/api_parser/utils.py
Labels: feature

#552 [API_PARSER][GATEWATCHER_ALERTS] Merge `raw_alert` into `alert` dict
  CHANGELOG
  vulture_os/toolkit/api_parser/gatewatcher_alerts/gatewatcher_alerts.py
Labels: enhancement

#558 [HORNETSECURITY] Add missing proxies/verify parameters to get_hierarchy_id()
  vulture_os/toolkit/api_parser/hornetsecurity/hornetsecurity.py
Labels: bug

#563 [API_PARSER] [TRENDMICRO_VISIONONE] HOTFIX :: Update last_api_call
  CHANGELOG
  vulture_os/toolkit/api_parser/trendmicro_visionone/trendmicro_visionone.py
Labels: bug
